# fly.toml app configuration file generated for search-frontend on 2023-05-18T04:18:00+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "search-frontend"
primary_region = "fra"

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
